# 1. URL base del Pooler
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres

# 2. Usuario específico del Pooler y Contraseña (sin corchetes)
spring.datasource.username=postgres.bbskcosygcgniivmbtwp
spring.datasource.password=Pepito2024++

# 3. Configuración del driver y JPA
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update