# URL del Pooler de Supabase (Compatible con IPv4)
spring.datasource.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:6543/postgres?prepareThreshold=0

# El usuario debe incluir el Project ID para usar el Pooler
spring.datasource.username=postgres.bbskcosygcgniivmbtwp

# Su contraseña configurada
spring.datasource.password=Pepito2024++

# Configuración del driver y JPA
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update