# Conexión a PostgreSQL en Supabase
spring.datasource.url=jdbc:postgresql://db.bbskcosygcgniivmbtwp.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Pepito2024++

# Configuración del driver y JPA
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update